# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveCocoa_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveCocoa_Demo
  #pod 'ReactiveCocoa'
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'MJExtension'

end
